version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo creating zip file in efs folder...
      - zip -r src.zip src
      - mkdir /test
      - mv src.zip /test
      - cd /test
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Mavern Pacakge...
      - cd ..
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo unzip the file...
      - cd /test
      - unzip -o src.zip -d /efs
      - ls -ltra
      - rm -rf src.zip
      - cd /efs
      - rm -rf src.zip
      - ls -ltra
