version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo creating zip file in /efs folder
      - cp -r docs /efs
      - cd /efs
      - ls -ltra
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Maven Pacakge...
      - cd ..
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
