version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo creating zip file in /test folder....
      - zip -r docs.zip docs
      - mkdir /test
      - mv docs.zip /test
      - cd /test
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Maven Pacakge...
      - cd ..
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo unzip the file...
      - cd /test
      - unzip -o docs.zip -d /efs
      - ls -ltra
      - rm -rf docs.zip
      - cd /efs
      - ls -ltra
      - rm -rf docs.zip
